#
# Executes commands at the start of an interactive session.
#

if [[ -s "${ZDOTDIR:-$HOME}/.lc-shell/zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.lc-shell/zsh/init.zsh"
fi


# ZSH options
setopt interactivecomments
