#
# Executes commands at login pre-zshrc.
#

# Make sure that zshenv is loaded and anything won't be
# override by the /etc/zprofile provided by the distro.
if [[ -f "${HOME}/.zshenv" ]]; then
  source "${HOME}/.zshenv"
fi
